# Generated by Django 3.0.7 on 2020-06-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dir', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=64)),
                ('in_scope', models.BooleanField(default=True, verbose_name='Whether or not this VM is in scope for this challenge.')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vctrl.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vctrl.VM')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('captured', models.BooleanField(default=False, verbose_name='Whether or not the student has found this flag.')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vctrl.VM')),
            ],
        ),
    ]
