# Generated by Django 3.0.7 on 2020-06-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vctrl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='duration',
            field=models.DurationField(verbose_name='Scenario time limit, in hours'),
        ),
    ]
