# Generated by Django 3.0.7 on 2020-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vctrl', '0002_auto_20200605_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='revertible',
            field=models.BooleanField(default=True, verbose_name='Whether or not the student is allowed to revert this machine.'),
        ),
    ]
