# Generated by Django 3.0.7 on 2020-06-08 22:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vctrl', '0003_vm_revertible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600),
                                       verbose_name='Scenario time limit, in hours'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 32, 42, 954785)),
        ),
    ]
