# Generated by Django 3.0.7 on 2020-06-08 22:35

import configparser
import datetime
import logging

from django.db import migrations

# TODO: Figure out whether or not hard coding this is absolutely necessary
CONFIG_FILE = "/scenario/scenario.ini"


def load_scenario(apps, schema_editor):
    """
    Uses a config parser to load enough information to generate an initial scenario entry into the dataset.
    This is helpful because we will have a Scenario object on-hand for when we create VM objects.
    :return: None
    """
    Scenario = apps.get_model('vctrl', 'Scenario')
    parser = configparser.ConfigParser()
    try:
        with open(CONFIG_FILE, "r") as ini_file:
            logging.debug("load_scenario: reading config from file in /scenario")
            parser.read_file(ini_file)
        s_name = parser.get("Scenario", "name")
        s_duration = parser.get("Scenario", "duration")
        s_description = parser.get("Scenario", "description")
        s_dir = "/scenario"
        # TODO: Do we want to put in an option to set this value?
        s_start = datetime.datetime.now()
        init_scenario = Scenario(name=s_name, start=s_start, dir=s_dir, duration=s_duration)
        init_scenario.save()

    except FileNotFoundError:
        # Load the default Scenario config located in the app root
        init_scenario = Scenario()
        init_scenario.save()


class Migration(migrations.Migration):
    dependencies = [
        ('vctrl', '0004_auto_20200608_1632'),
    ]

    operations = [
        migrations.RunPython(load_scenario)
    ]
