# Generated by Django 3.0.7 on 2020-06-09 20:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vctrl', '0005_auto_20200608_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.CharField(
                default='The default scenario that BSSM loads in the absence of a regular scenario.ini file',
                max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='dir',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 3, 47, 974080)),
        ),
    ]
